quest
AtremBi/java-shareit pull request #1
Opened 2023-07-09 22:20 UTC by AtremBi

2023-07-10 09:53 UTC, TomattmanYandex requested changes
Привет, комментов много, много переделывать

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private Date start;
используй лучше LocalDate, а конкретно в этом случае лучше подойдет LocalDateTime 
Date слегка устаревшая штука

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Date start;
аналогично про дату

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/enums/BookingStatus.java
> +package ru.practicum.shareit.enums;
енам относится к модели, так что можно запихнуть его туда же где и класс модели, а учитывая что пакетирование по фичам, то стоит в основной пакет booking закинуть

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exeptions/OwnerNotChangeException.java
> +    public OwnerNotChangeException(String message) {
немного не понятно что за ошибка и зачем она, но думаю позже разберусь

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/handler/CustomExceptionHandler.java
> +package ru.practicum.shareit.handler;
можно было бы в пакет к ошибкам закинуть

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (!checkItemInStorage(item.getId()) && userService.getUserById(userId) != null) {
лучше обрабатывать это по другому
1) чтобы метод getById возвращал optional 
2) получаем по id и записываем в переменную, если optional.isPresent значит в базе существует, и можно если надо использовать значение из переменной

проверку пользователя лучше сделать по другому, чтобы метод userService.getUserById кидал ошибку если пользователь не найден
и тогда можно просто выполнить
userService.getUserById
//код дальше выполнится только в том случае, если пользователь будет найден, если пользователь не найден, то падает ошибка, и выполнение дальше не идет

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (!text.isBlank()) {
удобнее проверять сначала крайние значение
 if (text.isBlank()){
  return new ArrayList();
}
//сюда код дойдет только если текст не пустой
и можно избежать дополнительной вложенности

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +            itemInMemory.getItems().forEach(item -> {
лучше это разрулить на уровне хранилища, сделать метод, который будет проходить по хранилищу и возвращать только найденные результаты

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private final ItemInMemory itemInMemory;
у нас есть интерфейс, почему не инжектить по нему сразу, и второе, зачем переменную называть itemInMemory в следующем спринте будет реализация в базе, на основе того же интерфейса, если назвать сразу ItemStorage itemStorage; то в  следующем спринте в сервисе возможно ничего не придётся менять, а так придётся и тип менять и название

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (checkItemInStorage(itemId)) {
зачем нам два вызова в хранилище, сначала проверка потом само получение, получаем сразу проверяем null ли, а лучше как я писал выше, чтобы возвращался optional и если не null то превращаем в дто, иначе кидаем ошибку
если сделать с optional то метод выглядеть будет примерно так
return itemStorage.getItemById().map(ItemMapper::toItemDto).orElseThrow(тут создать ошибку)

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +            throw new AlreadyExistException("Вещь не найдена");
почему вещь не найдена, а ошибка AlreadyExistException лучше для не найдено создать ошибку NotFoundException

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        itemInMemory.getItems().forEach(item -> {
Хранилище должно иметь метод, который вернет все айтемы по id  владельца

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (checkItemInStorage(item.getId()) && userService.getUserById(userId) != null
поп роверке пользователя я уже писал

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +            throw new AlreadyExistException("Вещь не найдена");
по поводу ошибки тоже писал

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private boolean ownerNotChange(Long userId, Long itemId) {
очень непонятно метод звучит
 назвать validateOwner или checkOvner а ошибку назвать PermissionException или WrongUserException

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    void deleteItem(Long itemId);
тут не хватает кучки методов

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/impl/ItemInMemory.java
> +package ru.practicum.shareit.item.impl;
с разделением на пакеты по фичам, мы не добавляем пакеты под имплементации, мапперы, модели, обычно храниться все в одном основном пакете
(дто будет много, поэтому имеет смысл их вынести в отдельный пакет)

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +package ru.practicum.shareit.user.model;
двигаем на пакет выше

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        if (checkUserInStorage(userId)) {
аналогично как с итемами, стоит переделать

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +            userDtos.add(UserMapper.toUserDto(user));
можно, и лучше сделать в маппере метод который будет мапить сразу список пользователей (перегрузить метод toUserDto чтобы принимался лист, а там логика будет точно такая же, пройтись по циклу и вызвать для каждого обекта метод с маппингом одного

2023-07-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    private boolean notExistEmail(UserDto userDto) {
это метод, метод это действие, и его следует отобразить в названии метода, с текущим именем, не понятно что за действие будет производиться

а еще лучше эту логику закинуть на уровень хранилища сделать метод isEmailExist который будет возвращать true или false

2023-07-12 23:07 UTC, AtremBi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (checkItemInStorage(itemId)) {
Не получилось  с optional

2023-07-13 11:39 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemInMemory.java
> +public class ItemInMemory implements ItemStorage {
кстати имя класса я не пометил, только потому что в следуюещм спринте надо будет все равно переделывать, а так лучше сразу давать нормальные имена, ибо что значит ItemInMemory

2023-07-13 11:39 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        items.forEach(item -> {
а почему бы стримы не использовать 
retrun items.stream().map(item -> toItemDto(item)).toList()

2023-07-13 11:39 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (checkItemInStorage(itemId)) {
падает null это nullPointer Или возвращается Null 
если первое, то в orElseThrow можно самому создать ошибку которую будет передатваться
если второе, то хз как у тебя получилось так 


[пример с ошибкой
[.[orElseThrow](https://www.tabnine.com/code/java/methods/java.util.Optional/orElseThrow)(() -> new IllegalStateException(
          "No HttpMessageWriter for \"" + mediaType + "\" and \"" + elementType + "\""));](https://www.tabnine.com/code/java/methods/java.util.Optional/orElseThrow)](https://www.tabnine.com/code/java/methods/java.util.Optional/orElseThrow)

2023-07-13 11:48 UTC, TomattmanYandex requested changes
надо еще переделывать, а раз уже передлывать надо, то стоит также поменять имена методов хранилище

2023-07-13 11:48 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        if (userStorage.isEmailExist(userDto)) {
если емейл существует, то создаем пользователя, иначе кидаем ошибку, или проблема в логике или проблема в именах

2023-07-13 11:48 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UsersInMemory.java
> +    public boolean isEmailExist(UserDto userDto) {
если назвали метод isEmailExist значит следует чтобы он возвращал true или false и не кидал ошибку

чтобы метд кидал ошибку лучше назвать его checkEmail но тогда он должен быть на уровне сервиса, хранилище не проверяет данные

2023-07-15 00:53 UTC, AtremBi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (checkItemInStorage(itemId)) {
![image](https://github.com/AtremBi/java-shareit/assets/93490879/25556012-440b-4e9b-973a-f686d4f6acdf)
![image](https://github.com/AtremBi/java-shareit/assets/93490879/e2cb4b52-35db-45d6-868a-c568ebda7b3b)
![image](https://github.com/AtremBi/java-shareit/assets/93490879/e3b815e9-258d-4560-a89f-c83ef8bfd15d)

хз, кучу всего перепробовал ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

2023-07-15 15:07 UTC, TomattmanYandex requested changes
все еще надо переделать

2023-07-15 15:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemHashMapStorage.java
> +public class ItemHashMapStorage implements ItemStorage {
излишние подробности в имени класса
хватило бы ItemInMemoryStorage

2023-07-15 15:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UsersHashMapStorage.java
> +
куда делся метод проверки email 
надо вернуть
просто изменить реализацию согласно комменту

а текущая версия не пойдет, потому что, для провекри одного email получать списки всех пользователей, плохой вариант

2023-07-16 11:38 UTC, TomattmanYandex requested changes
ну же, еще чуть чуть поднапрячься, сосредоточиться и внимательно доделать

2023-07-16 11:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        if (userStorage.isEmailExist(userDto)) {
так все еще немножко надо доделать
не имеет смысла чтобы этот метод одновременно возвращал boolean и кидал ошибку, надо оставить что то одно, либо кидаем ошибку, либо возвращаем boolean
если метод имеет имя isEmailExist то возвращаем boolean и ошибку не кидаем, как минимум тут,
если метод имеет имя checkEmail то не возвращаем ничего но если емейл существует кидаем ошибку

2023-07-16 11:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UsersInMemoryStorage.java
> +        return getUsers().stream().noneMatch(u -> u.getEmail().equals(userDto.getEmail()));
сейчас метод делает ровно противоположенное вовзвращает true если емейла не сущетвет, а судя по имени должен возвращать tкгу если email существует

2023-07-17 07:13 UTC, TomattmanYandex approved these changes
Принято

2023-07-17 07:13 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UsersInMemoryStorage.java
> +    public boolean isEmailExist(UserDto userDto) {
еще один момент, но пятая итерация и все равно в следующем спринте исправлять прийдется, на уровень репозитория мы не передаем Dto тем болле ради одного поля, уровень репозитория работает либо с моделями либо с стандартными типами (енамы это часть моделей)

2023-08-09 21:24 UTC, merged